[theme]
base = "dark"
primaryColor = "#2563eb"
backgroundColor = "#0e0e0e"
secondaryBackgroundColor = "#1c1c1c"
textColor = "#e5e5e5"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 200

[browser]
gatherUsageStats = false
